version: '3.7'

services:

  nginx:
    image: nginx
    volumes:
      - ./app:/code
      - ./services/nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    links:
      - php

  php:
    image: php:7.2-fpm
    environment:
      APACHE_DOCUMENT_ROOT: public/
      PHP_EXTENSION_XDEBUG: 1
      #PHP_MEMORY_LIMIT: 1G
      # Symfony
      APP_ENV: dev
      APP_SECRET: 8d2a5c935d8ef1c0e2b751147382bc75
      DATABASE_URL: mysql://foo:bar@mysql:3306/foo
    volumes:
      - ./app:/code

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: foo
      MYSQL_USER: foo
      MYSQL_PASSWORD: bar
    volumes:
      - mysql_data:/var/lib/mysql
      - ./services/mysql/utf8mb4.cnf:/etc/mysql/conf.d/utf8mb4.cnf:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    environment:
      PMA_HOST: mysql
      PMA_USER: foo
      PMA_PASSWORD: bar

volumes:
  mysql_data:
    driver: local